{"total_count": 24, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/geeklearningio/gl-vsts-tasks-azure/issues/44", "repository_url": "https://api.github.com/repos/geeklearningio/gl-vsts-tasks-azure", "labels_url": "https://api.github.com/repos/geeklearningio/gl-vsts-tasks-azure/issues/44/labels{/name}", "comments_url": "https://api.github.com/repos/geeklearningio/gl-vsts-tasks-azure/issues/44/comments", "events_url": "https://api.github.com/repos/geeklearningio/gl-vsts-tasks-azure/issues/44/events", "html_url": "https://github.com/geeklearningio/gl-vsts-tasks-azure/issues/44", "id": 491365663, "node_id": "MDU6SXNzdWU0OTEzNjU2NjM=", "number": 44, "title": "No backups were found to restore the database to the point in time", "user": {"login": "chrislaf", "id": 21255283, "node_id": "MDQ6VXNlcjIxMjU1Mjgz", "avatar_url": "https://avatars.githubusercontent.com/u/21255283?v=4", "gravatar_id": "", "url": "https://api.github.com/users/chrislaf", "html_url": "https://github.com/chrislaf", "followers_url": "https://api.github.com/users/chrislaf/followers", "following_url": "https://api.github.com/users/chrislaf/following{/other_user}", "gists_url": "https://api.github.com/users/chrislaf/gists{/gist_id}", "starred_url": "https://api.github.com/users/chrislaf/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/chrislaf/subscriptions", "organizations_url": "https://api.github.com/users/chrislaf/orgs", "repos_url": "https://api.github.com/users/chrislaf/repos", "events_url": "https://api.github.com/users/chrislaf/events{/privacy}", "received_events_url": "https://api.github.com/users/chrislaf/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 416158472, "node_id": "MDU6TGFiZWw0MTYxNTg0NzI=", "url": "https://api.github.com/repos/geeklearningio/gl-vsts-tasks-azure/labels/bug", "name": "bug", "color": "ee0701", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-09-09T22:57:50Z", "updated_at": "2020-07-01T09:38:03Z", "closed_at": "2020-07-01T09:38:03Z", "author_association": "NONE", "active_lock_reason": null, "body": "For this year the task has been running daily with out errors but over the last two month this error has started happening more and more. Now the error happens 99% of the time.\r\n\r\n1200003: No backups were found to restore the database to the point in time 9/9/2019 12:03:56 AM (UTC). Please contact support to restore the database.\r\n\r\nThe Azure database does not have a backup at that point in time. If I do a manual restore via Azure Portal the latest Restore Point available is about 5 min earlier.\r\n\r\nCan the task get the latest backup that is available  - not the backup at the exact time the task is run?\r\n\r\n", "reactions": {"url": "https://api.github.com/repos/geeklearningio/gl-vsts-tasks-azure/issues/44/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/geeklearningio/gl-vsts-tasks-azure/issues/44/timeline", "performed_via_github_app": null, "state_reason": "completed", "score": 1.0}]}