{"total_count": 22, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/tobania/VSTS.Extension.SqlReportingServices/issues/64", "repository_url": "https://api.github.com/repos/tobania/VSTS.Extension.SqlReportingServices", "labels_url": "https://api.github.com/repos/tobania/VSTS.Extension.SqlReportingServices/issues/64/labels{/name}", "comments_url": "https://api.github.com/repos/tobania/VSTS.Extension.SqlReportingServices/issues/64/comments", "events_url": "https://api.github.com/repos/tobania/VSTS.Extension.SqlReportingServices/issues/64/events", "html_url": "https://github.com/tobania/VSTS.Extension.SqlReportingServices/issues/64", "id": 1222845226, "node_id": "I_kwDOBOvE-c5I4yMq", "number": 64, "title": "The underlying connection was closed: An unexpected error occurred on a receive.", "user": {"login": "ndham", "id": 104771278, "node_id": "U_kgDOBj6uzg", "avatar_url": "https://avatars.githubusercontent.com/u/104771278?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ndham", "html_url": "https://github.com/ndham", "followers_url": "https://api.github.com/users/ndham/followers", "following_url": "https://api.github.com/users/ndham/following{/other_user}", "gists_url": "https://api.github.com/users/ndham/gists{/gist_id}", "starred_url": "https://api.github.com/users/ndham/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ndham/subscriptions", "organizations_url": "https://api.github.com/users/ndham/orgs", "repos_url": "https://api.github.com/users/ndham/repos", "events_url": "https://api.github.com/users/ndham/events{/privacy}", "received_events_url": "https://api.github.com/users/ndham/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2022-05-02T12:47:17Z", "updated_at": "2022-05-02T12:47:17Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "\r\n\r\nUsing this for my different environment. Not putting my production deployment and it starts the process and then stops in the middle giving this error \"The underlying connection was closed: An unexpected error occurred on a receive. 2022-05-01T12:00:59.6093931Z ##[error]PowerShell script completed with 1 errors.\" did anybody received that issue?\r\n\r\nThe timeout is set to 0\r\n", "reactions": {"url": "https://api.github.com/repos/tobania/VSTS.Extension.SqlReportingServices/issues/64/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/tobania/VSTS.Extension.SqlReportingServices/issues/64/timeline", "performed_via_github_app": null, "state_reason": null, "score": 1.0}]}