{"total_count": 205, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/microsoft/azure-devops-python-api/issues/458", "repository_url": "https://api.github.com/repos/microsoft/azure-devops-python-api", "labels_url": "https://api.github.com/repos/microsoft/azure-devops-python-api/issues/458/labels{/name}", "comments_url": "https://api.github.com/repos/microsoft/azure-devops-python-api/issues/458/comments", "events_url": "https://api.github.com/repos/microsoft/azure-devops-python-api/issues/458/events", "html_url": "https://github.com/microsoft/azure-devops-python-api/pull/458", "id": 1685434099, "node_id": "PR_kwDOBmuGes5PON0k", "number": 458, "title": "Update models to fix deserialization error", "user": {"login": "nechvatalp", "id": 38288693, "node_id": "MDQ6VXNlcjM4Mjg4Njkz", "avatar_url": "https://avatars.githubusercontent.com/u/38288693?v=4", "gravatar_id": "", "url": "https://api.github.com/users/nechvatalp", "html_url": "https://github.com/nechvatalp", "followers_url": "https://api.github.com/users/nechvatalp/followers", "following_url": "https://api.github.com/users/nechvatalp/following{/other_user}", "gists_url": "https://api.github.com/users/nechvatalp/gists{/gist_id}", "starred_url": "https://api.github.com/users/nechvatalp/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/nechvatalp/subscriptions", "organizations_url": "https://api.github.com/users/nechvatalp/orgs", "repos_url": "https://api.github.com/users/nechvatalp/repos", "events_url": "https://api.github.com/users/nechvatalp/events{/privacy}", "received_events_url": "https://api.github.com/users/nechvatalp/received_events", "type": "User", "site_admin": true}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2023-04-26T17:25:01Z", "updated_at": "2023-04-26T17:30:46Z", "closed_at": "2023-04-26T17:30:46Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/microsoft/azure-devops-python-api/pulls/458", "html_url": "https://github.com/microsoft/azure-devops-python-api/pull/458", "diff_url": "https://github.com/microsoft/azure-devops-python-api/pull/458.diff", "patch_url": "https://github.com/microsoft/azure-devops-python-api/pull/458.patch", "merged_at": "2023-04-26T17:30:46Z"}, "body": null, "reactions": {"url": "https://api.github.com/repos/microsoft/azure-devops-python-api/issues/458/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/microsoft/azure-devops-python-api/issues/458/timeline", "performed_via_github_app": null, "state_reason": null, "score": 1.0}]}